### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by eaba** [BayrakMustafa/WhatsApp-API-NET#1]
Hello @BayrakMustafa, others will love it if you created a pull request as this solves the strange character issuess indeed!

Regards

**Comment by BayrakMustafa** [comment]
Hi @eaba, I solved the strange character issuess by doing trim last character. I'dont know this method work all case. Can you test my code, please?

**Comment by eaba** [comment]
@BayrakMustafa your code works for me.
