### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by samuelg78** [BayrakMustafa/WhatsApp-API-NET#2]
I had just updated the 2 files (AxolotlManager.cs and SessionCipher.cs )to my project... and its not working. Error: Cannot decrypt message.

**Comment by eaba** [comment]
Comment out the lines that throws untrusted identity in sessionbuilder.process for now. Look at the issue i opened on untrustedidentityexception on mgp25 repo

**Comment by samuelg78** [comment]
I encountered the following error... pls help

![image](https://cloud.githubusercontent.com/assets/12243527/14401576/b0b12ab8-fe48-11e5-90e0-44a87a169ef1.png)

**Comment by eaba** [comment]
@samuelg78 this has to do with platform version incompatibility. For instance, WhatsTest platform version could be x64 while the WhatsAppi or Axolotl or mycurve platform version could be x86! Ensure all libs have the same platform version

**Comment by eaba** [comment]
Looks like you are using visual studio 2010? Is that correct? If yes, how did you build mycurve and axolotl? With what visual studio version?

**Comment by samuelg78** [comment]
@eaba Its working now for login and send chat. Its the mixed platforms debug mode that give the error. Is the registration code working?

**Comment by eaba** [comment]
@samuelg78 yes

**Comment by samuelg78** [comment]
@eaba The number registration is not working. The number will be blocked after 6-8 hours.

**Comment by eaba** [comment]
@samuelg78 have you tried it? and what was the result?

**Comment by samuelg78** [comment]
@eaba I already tried it.... u can register... no problem...But after running for 6-8hours whatsapp will start to block that number.

**Comment by samuelg78** [comment]
@eaba Please try it yourself. Only the registertool.php is working fine for now.

**Comment by eaba** [comment]
Well i have been using mine for over 10 hours.

**Comment by eaba** [comment]
Maybe you are doing something wrong

**Comment by samuelg78** [comment]
@eaba Thats weird.... i downloaded your project and register my number using WhatsAppPort's FrmRegister form....Is that correct?

**Comment by eaba** [comment]
I used the WhatsAppi RequestCode And RegisterCode method! Explore the WhatsAppApi Register Space!
