### ISSUE TITLE
Need help, Error File Not Found Exception ... MyCurve25519, Thank

### ISSUE THREAD

**Issue by mafaza86** [BayrakMustafa/WhatsApp-API-NET#3]
Hello @BayrakMustafa I Love your WhatsApp-API-NET, I say many thanks. 
![error wa mycurve](https://cloud.githubusercontent.com/assets/18475790/14550680/efb49fa0-02f4-11e6-83d0-06e891a4a286.png)

I have run WhatsTest, it run well. I use visual studio 2015, os windows 8 64 bit.
But i have a error, when i run WhatsTest in other PC (windows 7 64 bit).
Any one help me? Thank...

Regards

**Comment by BayrakMustafa** [comment]
Do you open project from WhatsAppApi_vs2015.sln file or WhatsAppWeb.sln? If you open from WhatsAppApi_vs2015.sln file, you can try WhatsAppWeb.sln file in MyCurve25519 folder. Because I can't add MyCurve25519 and MyLibAxolotl project to WhatsAppApi_vs2015.sln yet. If you open project from WhatsAppApi_vs2015.sln, you can't build MyLibAxolotl and MyCurve25519 project.

**Comment by eaba** [comment]
Hello @BayrakMustafa on my phone it says "chat sent to name are not end to end encrypted" I understand what the issue is, do you have any plans to update this Api further to like WA 2.0?

**Comment by mafaza86** [comment]
Thank you @BayrakMustafa  @eaba 
I open all project from WhatsAppWeb.sln from folder MyCurve25519.
It can load all project...
![waweb](https://cloud.githubusercontent.com/assets/18475790/14558120/dcb9bc60-032a-11e6-90bf-771cbbec309f.png)

**Comment by mafaza86** [comment]
hello, I have not found a solution.
I've tried to compile one at a project, and getting the same error, when I moved to another computer.
How to compile correct?
I've scanned with fuslog, mycurve also been loaded successfully.
Please help.
![waerrorlengkap](https://cloud.githubusercontent.com/assets/18475790/14562507/45e9de60-0347-11e6-88b0-64f8996bc0b2.png)

**Comment by eaba** [comment]
Platform incompatibility is possible! Ensure all your dll are compiled for the same platform, that is x86 or x64 in release mode! You can change the target platform by going to the project properties or configuration manager by right clicking on the solution!

**Comment by mafaza86** [comment]
Thank for your help @eaba 
I have compiled in 64 bit all. but i got the same error.
Have you tried to run on another pc?
This is my file 
![64bit](https://cloud.githubusercontent.com/assets/18475790/14564386/8a69af3a-0350-11e6-89f7-babb1469eeb3.png)

**Comment by eaba** [comment]
Do this: 
1 - Delete the MyCurve reference from Axolotl and re-add using the MyCurve compiled version. the     compile axolotl again!
2 - Delete Axolotl reference from WhatsAppApi and re-add using Axolotl compiled version and also add a reference to MyCurve to WhatAppApi. All other dependencies should be referenced in WhatsAppApi
In Summary Reference Compiled Versions and not the Projects!

**Comment by mafaza86** [comment]
![wapierrror](https://cloud.githubusercontent.com/assets/18475790/14566408/ad8bf5fa-0359-11e6-993d-7769a24f8ccf.png)
I have tried, but still error.

I Try to comment the code, the error is in this code :
`            if (_WhatsAppApi.LoadPreKeys() == null)
                _WhatsAppApi.SendSetPreKeys(true);`

But if i comment it, WhatsTest can't read message. But can send message normaly.
All error is when i run in another PC, in my development PC can run well.

**Comment by mafaza86** [comment]
When i compile MyLibAxolotl there are error warning, but compile is success...
`1>------ Build started: Project: MyLibAxolotl, Configuration: Release Any CPU ------
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "MyCurve25519", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
1>  MyLibAxolotl -> C:\wa\MyLibAxolotl\bin\Release\MyLibAxolotl.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
`

**Comment by eaba** [comment]
you know what? @BayrakMustafa has released compiled version, check under releases

**Comment by mafaza86** [comment]
Hello @eaba  @BayrakMustafa 
I have try for a long time... but my problem is not solved.
I have try to download from compiled release.
I have compiled with another pc vs 2012 32 bit, but get the same error...

Any one have tryed to run exe to another pc?
Thank you
![waerror2](https://cloud.githubusercontent.com/assets/18475790/14579525/783a394c-03d7-11e6-98be-d036492c97f9.png)

**Comment by BayrakMustafa** [comment]
Hello @mafaza86,
You can look this issues May be it help you. https://github.com/kwailo888/AxolotlTestApp/issues/19, https://github.com/kwailo888/AxolotlTestApp/issues/21
