### ISSUE TITLE
This project references NuGet package(s) that are missing on this computer

### ISSUE THREAD

**Issue by mafaza86** [BayrakMustafa/WhatsApp-API-NET#8]
Hi @BayrakMustafa @eaba 

I get some errors, when open the lasters whatsappapi, i try to add reference manual, but still error.
Any solution?
Thank You
![wa_erro_1](https://cloud.githubusercontent.com/assets/18475790/14802757/9165b7f4-0b7d-11e6-8c94-299fd94950dd.png)

Error		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\MyCurve25519\packages\System.Data.SQLite.Core.1.0.99.0\build\net45\System.Data.SQLite.Core.targets.	WhatsAppApi	C:\wa\WhatsAppApi\WhatsAppApi.csproj	182

**Comment by BayrakMustafa** [comment]
Hi @mafaza86 
I solved this error with last commit. You download last source code and try again.

**Comment by soothsayer1907** [comment]
Hello,

You didnt resolved this error.

2016-04-26 9:54 GMT+03:00 Mustafa Bayrak <notifications@github.com>:

**Comment by mafaza86** [comment]
Thank You @BayrakMustafa 
Great... work well...

**Comment by eaba** [comment]
Hello @BayrakMustafa we need to talk, questswa at gmail!
Thanks!
